### ISSUE TITLE
Some of the texts are missing

### ISSUE THREAD

**Issue by skinmaker1345** [weirdandwry/nr-local-spa#1]
While translating Nimby Rails into my native language, I found that some of the texts are missing in the official Spanish translation.
Some of the text such as Viaduct, Ground, Tram, Tunnel could not be translated, and the others were not even in the Spanish translation like "Maintenance". I occasionally found that the msgctxt for the Maintenance was "accounting_trains_maintenance", and I was able to translate although the word was not in the Spanish template. 

So I am curious about if there are other words  that can be translated but not in the original Spanish file.

![image](https://user-images.githubusercontent.com/45376950/106421388-f355db80-649f-11eb-99d9-730ae7000a1f.png)
![image](https://user-images.githubusercontent.com/45376950/106421491-27310100-64a0-11eb-98b0-4f8e67f76496.png)
![image](https://user-images.githubusercontent.com/45376950/106421020-3fece700-649f-11eb-89e6-08d32403e22a.png)

**Comment by weirdandwry** [comment]
Beta 1.1.22 will be able to show the track names in the localized language, but only after a game restart. 
There are missing words like the one you found. I am not updating the game.po file because the I am publishing beta builds very often, adding and replacing strings, and it would be a lot of work for both you and me. Once the 1.1.x series is more finished I will update the game.po file.

**Comment by skinmaker1345** [comment]
It seems that the game.po file is updated and the texts that were missing are now in the updated file.
